services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
    command: npm run dev -- --host
